name: MloppsassignC

on:
  issue_comment:
    types:
      - created

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: Just a simple demo job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: See full payload (for debugging)
        env:
          PAYLOAD: ${{ toJSON(github.event) }}
        run: |
          echo "FULL PAYLOAD:"
          echo "${PAYLOAD}"

      - name: Run the container and make a prediction
        if: startsWith(github.event.comment.body, '/predict')
        uses: ./
        id: make_prediction
        with:
          issue_comment_body: ${{ github.event.comment.body }}
          issue_number: ${{ github.event.issue.number }}
          issue_user: ${{ github.event.comment.user.login }}

      - name: Print the output from the container (for debugging)
        run: |
          echo "The reply message is:"
          echo "${{ steps.make_prediction.outputs.issue_comment_reply }}"

      - name: Send reply to issue for user
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         
